### ISSUE TITLE
Applying clothing overlay textures onto clothing meshes

### ISSUE THREAD

**Issue by HarryWang355** [PerceivingSystems/bedlam_render#27]
Thank you for the amazing work! I'm trying to apply the clothing overlay textures onto the raw clothing meshes in the rest pose (without the avatars). Directly applying image textures in Blender does not give any reasonable results. I suspect that the underlying UVs of the raw meshes are incompatible with the texture maps. Could you give any guidance on how we should proceed?

**Comment by tpsmpi** [comment]
The `clothing overlay textures` are in SMPL-X Blender add-on UV format so that they can be overlayed on top of the existing body textures to create body textures with clothing.

The 3D clothing assets have their own individual UV format. You can find the corresponding texture variations under the `Simulated clothing data` in the Downloads sections of the BEDLAM website.

**Comment by HarryWang355** [comment]
Good it. Thank you very much!
