### ISSUE TITLE
Clothing rest pose mesh low poly count

### ISSUE THREAD

**Issue by HarryWang355** [PerceivingSystems/bedlam_render#28]
Hi authors, I noticed that the clothing meshes in the rest pose do not have high poly counts. This leads to many visible artifacts (like in the example image), making the mesh look less realistic. I'm wondering if there is a version with higher quality meshes, or if there is a way for me to generate higher quality meshes at a reasonable cost. Any suggestion would be greatly appreciated!
![WechatIMG1942](https://github.com/user-attachments/assets/ae6c6ada-03b0-4fea-8d8a-26614cb3be94)

**Comment by tpsmpi** [comment]
We recommend that you post your above questions to our BEDLAM Clothing GitHub repo:
[https://github.com/PerceivingSystems/bedlam_clothing](https://github.com/PerceivingSystems/bedlam_clothing)

It's a better target location for your question since bedlam_render repo covers solely the rendering part.
