### ISSUE TITLE
clothing abc and npz file mismatch

### ISSUE THREAD

**Issue by BlackFox16** [PerceivingSystems/bedlam_render#3]
Hi,

I tried to load clothing as well as the corresponding groundtruth mocap sequence into Blender, but somehow I have a mismatch between those two animation sequences.

I have tested it with:

clothing file:
rp_aaron_posed_009/clothing_simulations/1074/1074.abc

groundtruth smplx:
gendered_ground_truth/rp_aaron_posed_009/moving_body_para/1074/motion_seq.npz

In Blender I also shifted the clothing mesh sequence with 100 to account for the frame offset 

<img width="301" alt="image" src="https://github.com/PerceivingSystems/bedlam_render/assets/118074019/aa389c4e-9a9c-4d1e-bd4d-2f6c7b83358f">

Result:

<img width="402" alt="image" src="https://github.com/PerceivingSystems/bedlam_render/assets/118074019/bb51a797-3376-40da-acf8-0fe8d0ed9cf8">

To solve the problem I would need to import smplx with clothing again in CLO3D and run the simulation, but I wonder if there is an easier solution before editing all those files manually again. 

Thanks!

**Comment by tpsmpi** [comment]
All the BEDLAM CLO exported clothing Alembic .abc files start at frame 100 and you have to apply a frame offset of -100 in the Blender MeshSequenceCache modifier to compensate for that since the Blender Alembic importer (unlike the Unreal Alembic importer) has no import setting for that. 
For specific questions regarding the clothing simulation part of BEDLAM please visit https://github.com/PerceivingSystems/bedlam_clothing

![clothing_blender_frame_offset](https://github.com/PerceivingSystems/bedlam_render/assets/60175755/d59f7da4-fe5b-423a-8993-a4014032c333)

**Comment by BlackFox16** [comment]
Ah I need to update the pose shapes, then it works, thanks
