### ISSUE TITLE
Orbit Camera Movement error

### ISSUE THREAD

**Issue by xnd-r** [PerceivingSystems/bedlam_render#9]
Hi, 
I have successfully created a level sequence with `camera_movement == "Static"`, but if I'm trying to change the camera movement parameter, e.g. to "Orbit", I'm getting the next error:

```
LogPython: Error: Cannot find LevelSequence camera template: /Game/Bedlam/CameraMovement/LS_Camera_Orbit
LogPython: Error: LevelSequence generation failed. Total time: 0.0s
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "C:/Program Files/Epic Games/UE_5.0/Engine/Content/PS/Bedlam/Core/Python/create_level_sequences_csv.py", line 732, in <module>
LogPython: Error:     sys.exit(1)
LogPython: Error: SystemExit: 1
```

Could you please give me some advice on how to solve this issue?

**Comment by tpsmpi** [comment]
Camera movement LevelSequence templates are used to modify camera extrinsics/intrinsics during a sequence. Since they modify Actors of your specific project Level you need to create them yourself. We do not provide code to automate this step.
`Orbit` template modifies the yaw of `BE_CameraRoot` and `Zoom` templates modify the focal length of the BE_CineCameraActor_Blueprint.

Below an example image for the `archVizUI3` orbit scenes where we keyframe `BE_CameraRoot` yaw from 90 to 180. End keyframe time is always automatically adjusted to sequence end time. See [create_level_sequences_csv.py](https://github.com/PerceivingSystems/bedlam_render/blob/main/unreal/render/Core/Python/create_level_sequences_csv.py) for additional information.

![LS_Camera_Orbit](https://github.com/PerceivingSystems/bedlam_render/assets/60175755/1b3ae2d3-5eec-4a41-9fbb-3c858055080f)

**Comment by xnd-r** [comment]
Thank you very much!
